version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ajith2243  
      POSTGRES_DB: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: backend-container
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: ajith2243
      DB_NAME: admin
      
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    container_name: frontend-container
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
